name: "Build — Debug iOS"

on:
  workflow_dispatch:

jobs:
  build-debug-ios:
    runs-on: self-hosted
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build debug iOS
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          FIREBASE_APP_ID_IOS: ${{ secrets.FIREBASE_APP_ID_IOS }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          BUILD_TYPE: debug
          PLATFORM: ios
          SCRIPTING_DEFINES: SIMPLE_DEBUG
        run: fastlane --fastfile ~/Developer/Simple-CI/templates/fastlane/Fastfile ios debug
